{% set name = "cwl-utils" %}
{% set version = "0.36" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b3b4cd1b24c14ec44ccdd6320a7957ebaf602a2ace17313c17b29d72fd6060c4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - cwl-cite-extract = cwl_utils.cite_extract:main
    - cwl-docker-extract = cwl_utils.docker_extract:main
    - cwl-expression-refactor = cwl_utils.expression_refactor:main
    - cwl-graph-split = cwl_utils.graph_split:main
    - cwl-normalizer = cwl_utils.normalizer:main

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - cwl-upgrader >=1.2.3
    # cwl-upgrader is for cwl-normalizer (cwl_utils/normalizer.py)
    - cwlformat
    # cwlformat is from extras[pretty], for cwl-graph-split. An alternative for this would be to build for
    # multiple outputs, e.g. https://github.com/conda-forge/matplotlib-feedstock/blob/2ca6433797f0a4f77fee890c6fa39617a6a6b0b4/recipe/meta.yaml#L17
    - packaging
    - rdflib
    - requests
    - schema-salad >=8.3.20220825114525,<9
    - ruamel.yaml >=0.17.6,<0.18

test:
  imports:
    - cwl_utils
  commands:
    - pip check
    - cwl-cite-extract --help
    - cwl-docker-extract --help
    - cwl-expression-refactor --help
    - cwl-graph-split --help
    - cwl-normalizer --help
    - python -m pytest -n auto --pyargs cwl_utils
  requires:
    - pip
    - pytest-xdist
    - pytest-mock
    - nodejs

about:
  home: https://github.com/common-workflow-language/cwl-utils
  license: Apache-2.0
  license_file:
    - LICENSE
  summary: Python utilities for CWL
  dev_url: https://github.com/common-workflow-language/cwl-utils/

extra:
  recipe-maintainers:
    - mr-c
    - kinow
